using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApiEFExample.Models
{
    public class Entity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]//switch on autogenerated        
        public int Id { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.None)]// switch off autogenerated PK
    }
}